export const GET_TWEET = "GET_TWEET";
export const CREATE_TWEET = "CREATE_TWEET";
export const UPDATE_TWEET = "UPDATE_TWEET";
export const DELETE_TWEET = "DELETE_TWEET";
export const GET_ALL_TWEETS_FROM_USER = "GET_ALL_TWEETS_FROM_USER";
export const GET_RELEVENT_TWEETS = "GET_RELEVENT_TWEETS";
export const TWEET_ERROR = "TWEET_ERROR";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";